version: '3.8'

services:
  web:
    build: .
    container_name: college_app_system
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: college_appointment_system
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend-demo:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: